config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{registrations:"users/registrations",sessions:"users/sessions"}
  devise_scope :user do
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
  end
  namespace :users do
    resources :shows, only: :show
    get "signout", to: "signouts#signout"
  end


  root "items#index"
  resources :items,except: :index do
    resources :payments, only: [:new, :create]
  end


  resources :categories, only: [:index, :show] do
    collection do
      get "ajax"
    end
  end


  resources :card, only: [:new, :create, :destroy]


  get "search", to: "searches#ajax"

end

app/models/item.rb
class Item < ApplicationRecord
  validates :name,                  presence: true, length: {maximum: 40}
  validates :description,           presence: true, length: {maximum: 1000}
  validates :condition_id,          presence: true
  validates :shipment_fee_id,       presence: true
  validates :prefecture_id,         presence: true
  validates :shipment_schedule_id,  presence: true
  validates :stock,                 presence: true, numericality:{only_integer: true,greater_than_or_equal_to: 0,less_than_or_equal_to: 9999}
  validates :price,                 presence: true, numericality:{only_integer: true,greater_than_or_equal_to: 300,less_than_or_equal_to: 9999999}

  validates_associated :images
  validates :images,                presence: true
  validate :images_length_validate

  def images_length_validate
    image_max = 10
    errors.add(:images, "は#{image_max}枚以下にしてください") if self.images.size > image_max
  end

  belongs_to :user
  belongs_to :category
  has_many :payments

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images,allow_destroy: true#, limit:10

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :condition
  belongs_to :shipment_fee
  belongs_to :prefecture
  belongs_to :shipment_schedule
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item,          except: [:index,:new,:create]
  before_action :set_category,      except: [:destroy]
  before_action :authenticate_user!,except: [:index,:show]

  def index
    @items = Item.order(created_at:"DESC").limit(5).includes(:images)
  end

  def show
    @item_ancestors = @item.category.ancestors
    @items = Item.where(category_id:@item.category_id).order(created_at:"DESC").limit(5).includes(:images)
  end

  def new
    @item = Item.new
    @item.images.build
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to new_item_path
    else
      render :new
    end
  end

  def update
    if @item.user_id == current_user.id && @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @item.user_id == current_user.id && @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :category_id,
      :brand,
      :condition_id,
      :shipment_fee_id,
      :prefecture_id,
      :shipment_schedule_id,
      :stock,
      :price,
      images_attributes:[
        :image,
        :image_cache,
        :id,
        :_destroy,
      ],
    ).merge(user_id:current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_category
    @categories = Category.order(id:"ASC").where(ancestry:nil)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_with model:@item,local:true do |f|

  .item__image
    .item__image--title
      出品画像
      %span 必須
    %p.item__image--note 最大10枚までアップロードできます
    .item__image--upload
      = f.fields_for :images do |img|
        .item__image--uploadBox
          = img.label :image,class:"click_label" do
            = icon('fa','camera')
            - if params[:action]=="new"
              = img.file_field :image,accept:"image/*",data:{index: img.index},name:"item[images_attributes][#{img.index}][image]",multiple:true,required:true
            - else
              = image_tag @item.images[img.index].image_url
              = img.file_field :image,accept:"image/*",data:{index: img.index}
          %span.item_image--delete 削除
          %span.item_image--change 変更
          = img.hidden_field :image_cache if params[:action]=="create"||params[:action]=="update"
          = img.check_box:_destroy if params[:action]=="edit"||params[:action]=="update"
      - unless params[:action]=="new"
        .item__image--uploadBox
          %label.click_label{for:"item_images_attributes_#{@item.images.length}_image"}
            = icon('fa','camera')
            %input{type:"file",id:"item_images_attributes_#{@item.images.length}_image",accept:"image/*","data-index":"#{@item.images.length}",name:"item[images_attributes][#{@item.images.length}][image]",multiple:"multiple"}
          %span.item_image--delete 削除
          %span.item_image--change 変更
    - if @item.errors.messages[:images].present?
      %p.item__image--err= @item.errors.messages[:images]

  .item__detail
    %p.item__detail_heading 商品の詳細
    .item__detail_name
      .item__detail_name--title
        商品名
        %span 必須
      = f.text_field :name,placeholder:"40字まで",class:"item__description_name--input",maxlength:"40",required:true
      - if @item.errors.messages[:name].present?
        %p.item__description_name--err 入力してください
    .item__detail_category
      .item__detail_category--title
        カテゴリー
        %span 必須
      = f.collection_select :category_id, @categories,                    :id,:name,{prompt:"選択してください",selected:"#{@item.category.root_id if @item.category}"}, {id:"item_category_parents",  class:"item__detail_category--select",required:true}
      = f.collection_select :category_id, @item.category.parent.siblings, :id,:name,{prompt:"選択してください",selected:"#{@item.category.parent_id}"},                 {id:"item_category_parent",   class:"item__detail_category--select",required:true}  if @item.category && @item.category.depth > 1
      = f.collection_select :category_id, @item.category.siblings,        :id,:name,{prompt:"選択してください",selected:"#{@item.category.id}"},                        {id:"item_category",          class:"item__detail_category--select",required:true}  if @item.category && @item.category.depth > 0
      - if @item.errors.messages[:category_id].present?
        %p.item__detail_category--err 選択してください
    .item__detail_brand
      .item__detail_brand--title
        ブランド
      = f.text_field :brand,{placeholder:"例）ユニクロ", class:"item__detail_brand--input"}
    .item__detail_condition
      .item__detail_condition--title
        商品の状態
        %span 必須
      = f.collection_select :condition_id,Condition.all,:id,:name,{prompt:"選択してください"},{class:"item__detail_condition--select",required:true}
      - if @item.errors.messages[:condition_id].present?
        %p.item__detail_condition--err 選択してください
    .item__detail_textarea
      .item__detail_textarea--title
        商品の説明
        %span 必須
      = f.text_area :description,placeholder:"1000文字まで", rows:7,class:"item__detail_textarea--textarea",maxlength:"1000",required:true
      - if @item.errors.messages[:description].present?
        %p.item__detail_textarea--err 入力してください
      %p.item__detail_textarea--count 0/1000

  .item__shipment
    %p.item__shipment_heading 配送について
    .item__shipment_fee
      .item__shipment_fee--title
        配送料の負担
        %span 必須
      = f.collection_select :shipment_fee_id,ShipmentFee.all,:id,:name,{prompt:"選択してください"},{class:"item__shipment_fee--select",required:true}
    - if @item.errors.messages[:shipment_fee_id].present?
      %p.item__shipment_fee--err 選択してください
    .item__shipment_region
      .item__shipment_region--title
        発送元の地域
        %span 必須
      = f.collection_select :prefecture_id,Prefecture.all,:id,:name,{prompt:"選択してください",selected:"#{current_user.address.prefecture_id}"},{class:"item__shipment_region--select",required:true}
    - if @item.errors.messages[:prefecture_id].present?
      %p.item__shipment_region--err 選択してください
    .item__shipment_schedule
      .item__shipment_schedule--title
        発送までの日数
        %span 必須
      = f.collection_select :shipment_schedule_id,ShipmentSchedule.all,:id,:name,{prompt:"選択してください"},{class:"item__shipment_schedule--select",required:true}
    - if @item.errors.messages[:shipment_schedule_id].present?
      %p.item__shipment_schedule--err 選択してください

  .item__stock
    %p.item__stock_heading 販売個数
    .item__stock--title
      個数
      %span 必須
    - if params[:action]=="new" || params[:action]=="create"
      = f.number_field :stock,class:"item__stock--input",placeholder:"1〜9,999",min:"1",max:"9999",step:"1",required:true
      - if @item.errors.messages[:stock].present?
        %p.item__stock_quantity--err 入力してください
    - else
      = f.number_field :stock,class:"item__stock--input",placeholder:"0〜9,999",min:"0",max:"9999",step:"1",required:true
      - if @item.errors.messages[:stock].present?
        %p.item__stock_quantity--err 入力してください

  .item__price
    %p.item__price_heading 価格
    .item__price--title
      販売価格入力
      %span 必須
    = f.number_field :price,class:"item__price--input",placeholder:"300〜9,999,999",min:"300",max:"9999999",step:"1",required:true
    - if @item.errors.messages[:price].present?
      %p.item__price--err 300以上9999999以下で入力してください
    .item__price--price
      %p 販売価格
      %span ---
    .item__price--tax
      %p 販売手数料（10%）
      %span ---
    .item__price--profit
      %p 販売利益
      %span ---

  .item__send
    = f.submit "#{params[:action]=="edit"||params[:action]=="update" ? "変更する" : "出品する"}",class:"item__send--button"
    = link_to "戻る", root_path, class: "item__send--back"
    .item__send--note
      %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/edit.html.haml
.itemEdit
  = render "form"

app/views/items/index.html.haml
.itemIndex
  %section.topVisual
    .topVisual__inner
      %h2.topVisual__inner--subTitle
        人生を変えるフリマアプリ
      %p.topVisual__inner--text
        FURIMAはだれでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .topVisual__inner--btn
        =link_to image_tag("icon/app-store.svg"),root_path,class:"aBtn"
        =link_to image_tag("icon/google-play.svg"),root_path,class:"gBtn"
  %section.topIntroduction
    %h2.subTitle
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        = image_tag("pict/pict-reason-01.jpg",class:"list--pict")
        %h3.list--text
          %span 3分
          ですぐに出品
        %p.list--description スマホで入力するだけで簡単に出品できる！
      %li.list
        = image_tag("pict/pict-reason-02.jpg",class:"list--pict")
        %h3.list--text
          %span シンプル
          で使いやすい
        %p.list--description めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        = image_tag("pict/pict-reason-03.jpg",class:"list--pict")
        %h3.list--text
          手数料
          %span 業界最安
        %p.list--description 最大3%でお得に出品&amp;購入！
  %section.middleVisual
    .middleVisual__inner
      %h2.middleVisual__inner--subTitle 会員数日本一位
      %p.middleVisual__inner--text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .middleVisual__inner--btn
        =link_to image_tag("icon/app-store.svg"),root_path,class:"aBtn"
        =link_to image_tag("icon/google-play.svg"),root_path,class:"gBtn"
  %section.middleIntroduction
    %h2.subTitle
      FURIMAの特徴
    %ul.lists
      %li.list
        = image_tag("icon/icon-01.png",class:"list--pict")
        %h3.list--text 簡単に売り買いできる
        %p.list--description スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.list
        = image_tag("icon/icon-02.png",class:"list--pict")
        %h3.list--text 売上金は即日振込みに対応
        %p.list--description 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.list
        = image_tag("icon/icon-03.png",class:"list--pict")
        %h3.list--text 様々な支払いに対応
        %p.list--description お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickupContainer
    %h2.pickupContainerTitle ピックアップカテゴリー
    = link_to root_path do
      %h3.pickupContainerSubtitle 新規投稿商品
    .pickupContainerProducts
      - @items.each do |item|
        .pickupContainerProductsList
          = link_to item_path(item.id) do
            - if item.stock==0
              .pickupContainerProductsSoldout
            .pickupContainerProductsList__img= image_tag item.images[0].image.url
            .pickupContainerProductsList__body
              %h3.pickupContainerProductsList__body--title= item.name
              %ul.pickupContainerProductsList__body--details
                %li= item.price
                %li 1
              %p (税込)
  %section.pickupContainer
    %h2.pickupContainerTitle ピックアップブランド
    = link_to root_path do
      %h3.pickupContainerSubtitle アーカイバ
    .pickupContainerProducts
      - @items.each do |item|
        .pickupContainerProductsList
          = link_to item_path(item.id) do
            - if item.stock==0
              .pickupContainerProductsSoldout
            .pickupContainerProductsList__img= image_tag item.images[0].image.url
            .pickupContainerProductsList__body
              %h3.pickupContainerProductsList__body--title= item.name
              %ul.pickupContainerProductsList__body--details
                %li= item.price
                %li 1
              %p (税込)

app/views/items/new.html.haml
.itemNew
  = render "form"

app/views/items/show.html.haml
.itemShow
  .itembox
    %div.itembox__name= @item.name
    .itembox__body
      .itembox__body--slider
        - @item.images.each do |image|
          .itembox__body--slider__img= image_tag image.image.url
      .itembox__body--thumbnail
        - @item.images.each_with_index do |image,index|
          %div{"data-index":"#{index}",ontouchstart:""}= image_tag image.image.url
      .itembox__price--price
        %span= @item.price
        %span 円
      .itembox__price--detail
        %span (税込)
        %span= @item.shipment_fee.name
    .itembox__detail= simple_format(@item.description)
    %table.itembox__table
      %tr
        %th 出品者
        %td= @item.user.nickname
      %tr
        %th カテゴリー
        %td
          - @item_ancestors.each do |ancestor|
            = link_to ancestor.name,category_path(ancestor.id)
          = link_to @item.category.name,category_path(@item.category.id)
      %tr
        %th ブランド
        %td= @item.brand
      %tr
        %th  商品の状態
        %td= @item.condition.name
      %tr
        %th 配送料の負担
        %td= @item.shipment_fee.name
      %tr
        %th 発送元の地域
        %td= @item.prefecture.name
      %tr
        %th 発送日の目安
        %td= @item.shipment_schedule.name
    - if current_user && current_user.id == @item.user_id
      = link_to '商品の編集',edit_item_path(@item.id),class:"itembox__edit"
      = link_to 'この商品を削除',item_path(@item.id),class:"itembox__delete",method: :delete
    - elsif current_user && current_user.id != @item.user_id && @item.stock!=0
      = link_to '購入画面に進む',new_item_payment_path(@item.id),class:"itembox__payment"

  - if current_user && current_user.id != @item.user_id
    .commentbox
      %form
        %textarea.commentbox__body
        %p.commentbox__note
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %button.commentbox__btn{name: "button", type: "submit"} コメントする

  .relatedbox
    .relatedbox__links
      = link_to "前の商品",root_path,class:"relatedbox__links--rev"
      = link_to "後の商品",root_path,class:"relatedbox__links--for"
    = link_to "#{@item.category.name}をもっと見る",category_path(@item.category.id),class:"relatedbox__anchor"
    .relatedbox__lists
      - @items.each do |item|
        .relatedbox__listsList
          = link_to item_path(item.id) do
            - if item.stock==0
              .relatedbox__listsSoldout
            .relatedbox__listsList__img= image_tag item.images[0].image.url
            .relatedbox__listsList__body
              %h3.relatedbox__listsList__body--title= item.name
              %ul.relatedbox__listsList__body--details
                %li= item.price
                %li 1
              %p (税込)