config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{registrations:"users/registrations",sessions:"users/sessions"}
  devise_scope :user do
    get "addresses", to: "users/registrations#new_address"
    post "addresses", to: "users/registrations#create_address"
  end
  namespace :users do
    resources :shows, only: :show
    get "signout", to: "signouts#signout"
  end


  root "items#index"
  resources :items,except: :index do
    resources :payments, only: [:new, :create]
  end


  resources :categories, only: [:index, :show] do
    collection do
      get "ajax"
    end
  end


  resources :card, only: [:new, :create, :destroy]


  get "search", to: "searches#ajax"

end

app/models/card.rb
class Card < ApplicationRecord
  validates :user, uniqueness: true
  validates :customer_id,:card_id, presence: true

  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :authenticate_user!

  def new
    if current_user&.card
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(current_user.card.customer_id)
      @card = customer.cards.retrieve(current_user.card.card_id)
    else
      @api_key = ENV["PAYJP_PUBLIC_KEY"]
    end
  end

  def create
    @api_key = ENV["PAYJP_PUBLIC_KEY"]
    if params["payjp-token"]
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.create(
        card: params["payjp-token"]
      )
      @card = Card.new(
        user_id: current_user.id,
        customer_id: customer.id,
        card_id: customer.default_card
      )
      if @card.save
        redirect_to new_card_path
      else
        render :new
      end
    else
      render :new
    end
  end

  def destroy
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    customer = Payjp::Customer.retrieve(current_user.card.customer_id)
    @card = Card.find(params[:id])
    if @card.destroy && customer.delete
      redirect_to users_show_path(current_user)
    else
      @err="no_cardDelete"
      render :new
    end
  end

end

app/views/card/new.html.haml
.contents
  = render "users/left_side_menu"
  .contents__right
    - if current_user&.card
      .contents__right__head
        %h3 クレジットカード情報

      .contents__right__body
        .card--brand= @card.brand
        %label カード番号
        .card--num= "**** **** **** #{@card.last4}"

        - if @card.name
          %label カード名義
          .card--name= @card.name

        - if @err
          .card_err "削除出来ませんでした"

        =link_to "削除",card_path(current_user.card), method: :delete,class:"contents__right__body-btn"
    - else
      .contents__right__head
        %h3 クレジットカード情報入力
      = form_with url: card_index_path,local:true,id:"card__form",class:"contents__right__body" do |f|
        %input#card__form--inputHidden{type:"hidden",name:"payjp-token"}

        %label カード番号
        %span.contents__right__body-require 必須
        #card__form--number-form.payjs-outer

        %label 有効期限
        %span.contents__right__body-require 必須
        #card__form--expiry-form.payjs-outer

        %label CVCコード
        %span.contents__right__body-require 必須
        #card__form--cvc-form.payjs-outer

        %label カード名義
        %span.contents__right__body-require 必須
        = f.text_field :name,id:"card__form--name",class:"payjs-outer"

        - if @err
          .card_err "暫く時間を置いてから再度お試し下さい"

        #card__form--errMessage
        = f.submit "登録する",id:"card__form--submit",class:"contents__right__body-btn"





%script{src: "https://js.pay.jp/v2/pay.js", type: "text/javascript"}

:javascript

  if("#{@api_key}"){

    const style = {
      base: {
        backgroundColor:'#ffffff',
        textAlign:'right',
        '::placeholder': {
          color: '#bbbbbb',
        }
      },
      invalid: {
        color: 'red',
      }
    }
    const stylenum = {
      base: {
        backgroundColor:'#ffffff',
        textAlign:'center',
        '::placeholder': {
          color: '#ffffff',
        }
      },
      invalid: {
        color: 'red',
      }
    }

    let payjp         = Payjp("#{@api_key}");
    let elements      = payjp.elements();
    let numberElement = elements.create('cardNumber', {style: stylenum});
    let expiryElement = elements.create('cardExpiry', {style: style});
    let cvcElement    = elements.create('cardCvc', {style: style});

    numberElement.mount('#card__form--number-form');
    expiryElement.mount('#card__form--expiry-form');
    cvcElement.mount('#card__form--cvc-form');

    $(".contents").on("click","#card__form--submit",function(e){
      e.preventDefault();

      payjp.createToken(numberElement,{card:{name:`${$("#card__form--name").val()}`}}).then(function(response){
        if(response.error){
          $('#card__form--errMessage').text(response.error.message);
        }else if(!$("#card__form--name").val()){
          $('#card__form--errMessage').text("カード名義をご入力下さい。");
        }else if(!$("#card__form--name").val().match(/^[A-Z]+ [A-Z]+$/)){
          $('#card__form--errMessage').text("カード名義のフォーマットが違います。");
        }else{
          $("#card__form--inputHidden").attr("value",response.id);
          $("#card__form").submit();
        }
      });
    });
  }